---
name: "Provider Lens"
guid: "ba6a4ff6-a27f-46e7-94ab-effb7dc39158"
version: 1
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "See stream providers for your libraries."
description: >
  Longer Description.

category: "General"
artifacts:
  - "Jellyfin.Plugin.ProviderLens.dll"
changelog: |-
